---
title: Concepts
---



EditorsRepo.jl lets you work with files of editing work in progress in a local file system using more abstract structures such as "a corpus of citable texts" (`CitableText.Corpus`) or "a record associating texts, image and physical surface" (from the `CitablePhysicalText` module).

One important application built with EditorsRepo.jl is the Pluto notebook providing interactive validation and verification of work in progress. (You can find it in the `notebooks` directory of the template github repository [here](https://github.com/HCMID/validatormodel).)



## Define a repository

An `EditingRepository` works with three kinds of data: text editions, indexes of text passages to images and physical surfaces, and configuration data specifying how to transform the edition files into citable texts. The repository expects each type of data to be managed in a separate directory.  By default, their names are `editions`, `config` and `dse`.


The starting point for EditorsRepo.jl is a directory in a local file system that includes subdirectories for standard kinds of content: editions of texts, indexing of texts to citable images and surfaces, and configuration files.


## Text editions and configuration

### Files

The *catalog* file (default name: `catalog.cex`) is a CITE text catalog.  Its entries represent logical units.

The *citation* file (default name: `citation.cex`) is a delimited text file with entries representing physical files.  It is possible to have a single logical text edited in multiple physical files.




### Functions

Internally, `EditorsRepo` uses these functions to read the configuration of your text documents:

- `fileswithin`.  List all files that are contained by a given URN.
- `filescontaining`.  List all files that contain a given URN

The following functions use "contained by" logic.

- `o2converter`
- `diplomaticbuilder`
- `normalizedbuilder`
- `orthography`
