---
title: Tutorials
engine: julia
---

```{julia}
#| echo: false
#| warning: false
#| output: false
root = pwd()  |> dirname |> dirname 
```

## Organizing an editing repository


An editing repository must have three specifically identified directories:

1. a directory with configuration data (default name: `config`)
2. a directory with archival editions of texts (default name: `editions`)
3. a directory with data indexing texts, physical surfaces and source images to create a digital scholarly edition (default name: `dse`)

Tutorial:

- how to [set up an editing repository](./files/)

## The `EditingRepository` object

You create an `EditingRepository` by giving the `repository` function the root directory of your editing repository. We've predefined the variable `root` to refer to the root directory of the `EditorsRepo.jl` github project, and will use a sample editing repository in its `test/data` directory.

```{julia}
#| output: false
using EditorsRepo
repo = joinpath(root, "test", "data", "splitdocs")
r = repository(repo)
```


## Working with an `EditingRepository`

Start with one of these tutorials to learn about some things you can do with an editing repository.


- [Read text corpora](./texts/) from repository
- [Validate editing](./validation.qmd)

